injectEnvironmentFiles:
  - .env.defaults?
  - .env?

enableGlobalCache: true

enableScripts: false

afterInstall: 'yarn turbo run //#config-ci --log-order=stream'

packageExtensions:
  '@storybook/builder-vite@*':
    dependencies:
      vite: '*'
  '@storybook/core-common@*':
    dependencies:
      storybook: '*'
  '@storybook/csf-tools@*':
    dependencies:
      storybook: '*'
  '@storybook/preview-api@*':
    dependencies:
      storybook: '*'
  '@sveltejs/kit@*':
    dependencies:
      '@sveltejs/vite-plugin-svelte': '*'
  eslint-config-love@*:
    dependencies:
      '@typescript-eslint/utils': '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
  vite-plugin-istanbul@*:
    dependencies:
      vite: '*'

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'

changesetBaseRefs:
  - ${BASE_REF:-origin/main}

pnpIgnorePatterns:
  - ./apps/svelte-app
  - ./packages/unplugged

yarnPath: .yarn/releases/yarn-4.4.0.cjs

globalFolder: ${YARN_GLOBAL_FOLDER:-\}
