injectEnvironmentFiles:
  - .env.defaults?
  - .env?

nodeLinker: pnp

enableScripts: false

packageExtensions:
  '@storybook/builder-vite@*':
    dependencies:
      vite: '*'
  '@storybook/web-components@*':
    dependencies:
      lit: '*'
  '@vitest/mocker@*':
    dependencies:
      vite: '*'
  '@zeplin/storybook-inspector@*':
    dependencies:
      prettier: '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
  storybook@*:
    dependencies:
      react: '*'
      react-dom: '*'
  storybook-zeplin@*:
    dependencies:
      '@storybook/icons': '*'
      storybook: '*'
  vite-plugin-istanbul@*:
    dependencies:
      vite: '*'

plugins:
  - checksum: 44a06a583a46ab1e2de2a04c115868bea51f01a314f261b628fbf6d92b2be63c0d155be3d3094d440daf58ff3f263aba4c9384a1c60c5d26cc0db086ad990459
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.7.0/bundles/@yarnpkg/plugin-after-install.js'
  - checksum: e5e6e2885ab0e6521b70b0af7c6d8ca2c75dcae2403706fc4600a783b339a6530a476dafb9450c9436ca4050eb6bdee9b62e6e2cebfecf1e81dd709a2480dc07
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

changesetBaseRefs:
  - ${BASE_REF:-origin/main}

changesetIgnorePatterns:
  - '.yarn/versions/*'

pnpIgnorePatterns:
  - ./apps/next-app
  - ./packages/unplugged

globalFolder: ${YARN_GLOBAL_FOLDER:-.temp/.yarn/berry}

npmPublishRegistry: ${NPM_REGISTRY_URL:-https://registry.npmjs.org/}

npmAuthToken: ${NPM_AUTH_TOKEN:-}
