enableScripts: false

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "^7.0.0-rc.1"
      "react": "*"
      "react-dom": "*"
      "vite": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
