injectEnvironmentFiles:
  - .env.defaults?
  - .env?

enableGlobalCache: true

enableScripts: false

afterInstall: 'yarn exec turbo run //#config-ci'

packageExtensions:
  '@oclif/core@*':
    dependencies:
      '@types/node': '*'
      typescript: '*'
  '@storybook/builder-vite@*':
    dependencies:
      '@storybook/addon-docs': '*'
      react: '*'
      react-dom: '*'
      vite: '*'
  '@storybook/core-common@*':
    dependencies:
      '@storybook/html-vite': '*'
      '@storybook/react-vite': '*'
      react: '*'
      react-dom: '*'
      vite: '*'
  '@storybook/html-vite@*':
    dependencies:
      '@babel/core': '*'
      react: '*'
      react-dom: '*'
      vite: '*'
  '@storybook/test-runner@*':
    dependencies:
      detect-package-manager: '*'
      regenerator-runtime: '*'
      semver: '*'
  '@storybook/web-components-vite@*':
    dependencies:
      lit: '*'
  '@storybook/web-components@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@sveltejs/kit@*':
    dependencies:
      '@sveltejs/vite-plugin-svelte': '*'
  ansi-escapes@*:
    dependencies:
      typescript: '*'
  dotenv-vault@*:
    dependencies:
      opener: '*'
      tslib: '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
      react: '*'
      react-dom: '*'
  vite-plugin-istanbul@*:
    dependencies:
      vite: '*'

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'

changesetBaseRefs:
  - ${BASE_REF:-origin/main}

pnpIgnorePatterns:
  - ./apps/svelte-app
  - ./packages/unplugged

yarnPath: .yarn/releases/yarn-4.2.2.cjs
