enableGlobalCache: true

enableScripts: false

packageExtensions:
  "@storybook/builder-vite@*":
    dependencies:
      "@storybook/addon-docs": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/html-vite": "*"
      "@storybook/react-vite": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
  "@storybook/html-vite@*":
    dependencies:
      "@babel/core": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
  "@storybook/test-runner@*":
    dependencies:
      detect-package-manager: "*"
      regenerator-runtime: "*"
      semver: "*"
  "@storybook/web-components@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/web-components-vite@*":
    dependencies:
      lit: "*"
  ansi-escapes@*:
    dependencies:
      typescript: "*"
  dotenv-vault@*:
    dependencies:
      tslib: "*"
  eslint-config-next@*:
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  "@oclif/core@*":
    dependencies:
      "@types/node": "*"
      typescript: "*"
  vite-plugin-istanbul@*:
    dependencies:
      vite: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.4.0/bundles/@yarnpkg/plugin-after-install.js"

pnpIgnorePatterns:
  - ./apps/svelte-app

yarnPath: .yarn/releases/yarn-3.6.4.cjs
