enableScripts: false

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/html-vite": "*"
      "@storybook/react-vite": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
  "@storybook/html-vite@*":
    dependencies:
      "@babel/core": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
  "eslint-config-next@*":
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs

pnpIgnorePatterns:
  - ./apps/svelte-app
