injectEnvironmentFiles:
  - .env.defaults?
  - .env?

nodeLinker: pnp

enableScripts: false

packageExtensions:
  '@storybook/experimental-addon-test@*':
    dependencies:
      '@vitest/runner': '*'
  '@storybook/builder-vite@*':
    dependencies:
      vite: '*'
  '@storybook/core@*':
    dependencies:
      react: '*'
      react-dom: '*'
      node-stdlib-browser: '*'
  '@storybook/preview-api@*':
    dependencies:
      storybook: '*'
  '@vitest/mocker@*':
    dependencies:
      vite: '*'
  '@zeplin/storybook-inspector@*':
    dependencies:
      prettier: '*'
  eslint-config-next@*:
    dependencies:
      next: '*'
  node-stdlib-browser@*:
    dependencies:
      qs: '*'
  react-confetti@*:
    dependencies:
      react: '*'
  storybook-zeplin@*:
    dependencies:
      '@storybook/components': '*'
      '@storybook/manager-api': '*'
      'storybook': '*'
  vite-plugin-istanbul@*:
    dependencies:
      vite: '*'

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'

changesetBaseRefs:
  - ${BASE_REF:-origin/main}

changesetIgnorePatterns:
  - '.yarn/versions/*'

pnpIgnorePatterns:
  - ./apps/svelte-app
  - ./packages/unplugged

yarnPath: .yarn/releases/yarn-4.8.1.cjs

globalFolder: ${YARN_GLOBAL_FOLDER:-\}
