enableScripts: false

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
      react: "*"
      react-dom: "*"
      vite: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
