name: Release
description: Create a release commit and publish

inputs:
  strategy:
    description: The version strategy to run
    required: true
  tag:
    default: ""
    description: The distribute tag
  dry_run_publish:
    description: If "true", publish is disabled

runs:
  using: "composite"
  steps:
    - name: Apply versions
      run: yarn apply-versions --strategy ${{ inputs.strategy }}
      shell: bash
    - name: Get versions
      id: versions
      run: echo "semver=$(yarn ls-workspaces --format=semver --no-private)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Configure git user
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      shell: bash
    - name: Prepare commit
      if: ${{ inputs.strategy != '' && inputs.strategy != 'build' }}
      run: |
        git add .
        git commit -m "chore(version): ${{ inputs.strategy }} release" || true
      shell: bash
    - name: Tag the HEAD
      if: ${{ inputs.tag != '' && steps.versions.outputs.semver != '{}' }}
      run: |
        git tag -d ${{ inputs.tag }} || true
        git push origin --delete ${{ inputs.tag }} || true
        git tag ${{ inputs.tag }} -a -m "${{ steps.versions.outputs.semver }}"
        git push origin ${{ inputs.tag }}
      shell: bash
    - name: Publish
      if: steps.versions.outputs.semver != '{}'
      run: >-
        yarn workspaces foreach -A --no-private ${{ inputs.dry_run_publish == '' && '' || '-n' }}
        npm publish --tolerate-republish
        ${{ inputs.tag == '' && '' || format('--tag {0}', inputs.tag) }}
      shell: bash
