name: Release
description: Create a release commit and publish

inputs:
  prerelease:
    description: Set to 'true', if you wish to create a prerelease version
  tag:
    description: The distribute tag

runs:
  using: "composite"
  steps:
    - name: Apply versions
      run: yarn version apply --all ${{ inputs.prerelease == '' && '' || '--prerelease' }}
      shell: bash
    - name: Configure git user
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      shell: bash
    - name: Prepare commit
      run: |
        git add .
        git commit -m "chore(publish): update versions" || true
      shell: bash
    - name: Tag the HEAD
      if: ${{ inputs.tag != '' }}
      run: |
        git tag -d ${{ inputs.tag }} || true
        git tag ${{ inputs.tag }}
        git push origin ${{ inputs.tag }}
      shell: bash
    - name: Publish
      run: >-
        yarn workspaces foreach -An --no-private npm publish --tolerate-republish
        ${{ inputs.tag == '' && '' || format('--tag {0}', inputs.tag) }}
      shell: bash
