name: Release
description: Create a release commit and publish

inputs:
  strategy:
    default: build
    description: The version strategy to run
  tag:
    default: ""
    description: The distribute tag
  dry_run_publish:
    description: If "true", publish is disabled

runs:
  using: "composite"
  steps:
    - name: Apply versions
      id: versions
      run: echo "semver=$(yarn apply-versions --strategy ${{ inputs.strategy }})" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build
      if: steps.versions.outputs.semver != '{}'
      run: |
        echo ${{ steps.versions.outputs.semver }}
        yarn build
      shell: bash
    - name: Prepare commit
      if: ${{ inputs.strategy != '' && inputs.strategy != 'build' }}
      run: |
        git add .
        git commit -m "chore(version): ${{ inputs.strategy }} release" || true
      shell: bash
    - name: Tag the HEAD
      if: ${{ inputs.tag != '' && steps.versions.outputs.semver != '{}' }}
      run: |
        git tag -d ${{ inputs.tag }} || true
        git push origin --delete ${{ inputs.tag }} || true
        git tag ${{ inputs.tag }} -am '${{ steps.versions.outputs.semver }}'
        git push origin ${{ inputs.tag }}
      shell: bash
    - name: Publish
      if: steps.versions.outputs.semver != '{}'
      run: >-
        yarn workspaces foreach -A --no-private ${{ inputs.dry_run_publish != '' && '-n' || '' }}
        npm publish --tolerate-republish
        ${{ inputs.tag != '' && format('--tag {0}', inputs.tag) || '' }}
      shell: bash
