injectEnvironmentFiles:
  - .env.defaults

nodeLinker: pnpm

nmSelfReferences: false

afterInstall: yarn svelte-kit sync && cd ../../ && yarn install

packageExtensions:
  '@sveltejs/vite-plugin-svelte@*':
    dependencies:
      'kleur': '*'
  postcss-scss@*:
    dependencies:
      postcss: '*'
