injectEnvironmentFiles:
  - .env.defaults

nodeLinker: pnpm

nmSelfReferences: false

afterInstall: yarn svelte-kit sync && cd ../../ && yarn install

packageExtensions:
  postcss-scss@*:
    dependencies:
      postcss: '*'
