injectEnvironmentFiles:
  - .env.defaults

nodeLinker: node-modules

nmSelfReferences: false

afterInstall: yarn check && cd ../../ && yarn install

packageExtensions:
  postcss-scss@*:
    dependencies:
      postcss: '*'
