injectEnvironmentFiles:
  - .env.defaults

nodeLinker: ${YARN_NODE_LINKER:-pnpm}

nmSelfReferences: false

afterInstall: yarn svelte-kit sync && cd ../../ && yarn install

packageExtensions:
  postcss-scss@*:
    dependencies:
      postcss: '*'
