name: Auto approve
on: pull_request_target

permissions:
  pull-requests: read

jobs:
  auto-approve:
    if: endsWith(github.actor, '[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          client-id: ${{ secrets.BOT_APP_CLIENT_ID }}
      - name: Auto approve
        if: github.actor == format('{0}[bot]', steps.get_token.outputs.app-slug)
        uses: hmarr/auto-approve-action@05a696a09d381a5a0d142c755f7eacbb19eb6525 # v4
        with:
          github-token: ${{ secrets.GH_OWNER_TOKEN }}
