name: Auto approve
on: pull_request_target

permissions:
  pull-requests: read

jobs:
  auto-approve:
    if: endsWith(github.actor, 'psychobolt[bot]')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@05a696a09d381a5a0d142c755f7eacbb19eb6525 # v4
        with:
          github-token: ${{ secrets.GH_OWNER_TOKEN }}
