name: Auto approve
on: pull_request_target

jobs:
  auto-approve:
    if: endsWith(github.actor, 'psychobolt[bot]')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_OWNER_TOKEN }}
