name: Auto approve
on: pull_request_target

jobs:
  auto-approve:
    if: endsWith(github.actor, 'psychobolt[bot]')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        with:
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.BOT_APP_ID }}
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ steps.get_token.outputs.token }}
