name: Auto approve
on: pull_request_target

jobs:
  auto-approve:
    if: endsWith(github.actor, 'renovate[bot]')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.RENOVATE_GH_TOKEN }}
