on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  chromatic:
    name: Run Chromatic
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Unpack binaries
        run: yarn install
      - run: cd ${{ inputs.path }} && yarn turbo chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}