on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  chromatic:
    name: Run Chromatic
    timeout-minutes: 15
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: yarn turbo chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}