name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1.11.6
        with:
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.14
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
        with:
          configurationFile: renovate.config.cjs
          token: '${{ steps.get_token.outputs.token }}'
