on:
  workflow_call:
    outputs:
      package_names: 
        value: ${{ jobs.diff.outputs.package_names }}

jobs:
  diff:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      package_names: ${{ steps.changes.outputs.package_names }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Collect Turborepo Changes
        id: changes
        uses: 94726/action-turborepo-changes@v1.1.0
        with:
          from: ${{ github.event.inputs.change-from || 'HEAD^1' }}
    