on:
  workflow_call:
    outputs:
      package_names: 
        value: ${{ jobs.diff.outputs.package_names }}

jobs:
  diff:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      package_names: ${{ steps.changes.outputs.package_names }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install Turbo
        run: npm install -g turbo@1.9.3
      - name: Collect Turborepo Changes
        id: changes
        uses: 94726/action-turborepo-changes@v1.1.0
        with:
          from: ${{ github.event.inputs.change-from || 'HEAD^1' }}
    