name: Packages

on:
  push:
    paths: packages/**
  workflow_dispatch:
    inputs:
      change-from:
        type: string

jobs:
  diff:
    uses: ./.github/workflows/diff.yml

  commons:
    needs: diff
    uses: ./.github/workflows/test-commons.yml
    if: contains(fromJSON(needs.diff.outputs.package_names), 'commons')

  html-ui:
    needs: diff
    uses: ./.github/workflows/test-package.yml
    if: contains(fromJSON(needs.diff.outputs.package_names), 'html-ui')
    with:
      workspace: html-ui
      path: packages/html-ui
    secrets: inherit

  react-ui:
    needs: diff
    if: contains(fromJSON(needs.diff.outputs.package_names), 'react-ui')
    uses: ./.github/workflows/test-package.yml
    with:
      workspace: react-ui
      path: packages/react-ui
    secrets: inherit
