name: Packages

on:
  push:
    paths: packages/**
  workflow_call:
    inputs:
      ref_name:
        type: string
        required: true
      change-from:
        type: string
  workflow_dispatch:
    inputs:
      change-from:
        type: string

jobs:
  diff:
    uses: ./.github/workflows/diff.yml
    with:
      ref_name: ${{ inputs.ref_name }}
      change-from: ${{ inputs.change-from }}

  commons:
    needs: diff
    uses: ./.github/workflows/test-commons.yml
    with:
      ref_name: ${{ inputs.ref_name }}
    if: contains(fromJSON(needs.diff.outputs.package_names), 'commons')

  html-ui:
    needs: diff
    uses: ./.github/workflows/deploy-package.yml
    if: contains(fromJSON(needs.diff.outputs.package_names), 'html-ui')
    with:
      ref_name: ${{ inputs.ref_name }}
      workspace: html-ui
      path: packages/html-ui
    secrets: inherit

  react-ui:
    needs: diff
    if: contains(fromJSON(needs.diff.outputs.package_names), 'react-ui')
    uses: ./.github/workflows/deploy-package.yml
    with:
      ref_name: ${{ inputs.ref_name }}
      workspace: react-ui
      path: packages/react-ui
    secrets: inherit
