name: Packages

on:
  workflow_call:
    inputs:
      ref_name:
        type: string
      package_names:
        type: string
        required: true
    outputs:
      release:
        value: "true"

jobs:
  commons:
    uses: ./.github/workflows/test-commons.yml
    with:
      ref_name: ${{ inputs.ref_name }}
    if: contains(fromJSON(inputs.package_names), 'commons')

  html-ui:
    uses: ./.github/workflows/deploy-package.yml
    if: contains(fromJSON(inputs.package_names), 'html-ui')
    with:
      ref_name: ${{ inputs.ref_name }}
      workspace: html-ui
      path: packages/html-ui
    secrets: inherit

  react-ui:
    if: contains(fromJSON(inputs.package_names), 'react-ui')
    uses: ./.github/workflows/deploy-package.yml
    with:
      ref_name: ${{ inputs.ref_name }}
      workspace: react-ui
      path: packages/react-ui
    secrets: inherit
