on:
  push:
    paths:
      packages/**
  workflow_dispatch:

jobs:
  diff:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Collect Turborepo Changes
        id: changes
        uses: 94726/action-turborepo-changes@v1.1.0
        with:
          from: HEAD^1
      - name: Write to output
        run: echo "package_names=${{steps.changes.outputs.package_names}}" >> $GITHUB_OUTPUT

  html-ui:
    needs: diff
    if: ${{ contains(fromJSON('${{needs.diff.outputs.package_names}}'), 'html-ui') == 'true' }}
    uses: ./.github/workflows/chromatic.yml
    with:
      workspace: html-ui
      path: packages/html-ui
    secrets: inherit

  react-ui:
    needs: diff
    if: ${{ contains(fromJSON('${{needs.diff.outputs.package_names}}'), 'react-ui') == 'true' }}
    uses: ./.github/workflows/chromatic.yml
    with:
      workspace: react-ui
      path: packages/react-ui
    secrets: inherit