on:
  workflow_call:
    inputs:
      packages:
        required: true
        type: string

jobs:
  html-ui:
    uses: ./.github/workflows/chromatic.yml
    with:
      environment: html-ui
    secrets: inherit

  react-ui:
    uses: ./.github/workflows/chromatic.yml
    with:
      environment: react-ui
    secrets: inherit