on:
  push:
    paths:
      packages/**
  workflow_dispatch:
    inputs:
      change-from:
        type: string
        default: HEAD^1

jobs:
  diff:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Collect Turborepo Changes
        id: changes
        uses: 94726/action-turborepo-changes@v1.1.0
        with:
          from: ${{ github.event.inputs.change-from }}
      - name: Write to output
        run: echo "package_names=${{toJSON(steps.changes.outputs.package_names)}}" >> $GITHUB_OUTPUT

  html-ui:
    needs: diff
    uses: ./.github/workflows/chromatic.yml
    if: contains(fromJSON(needs.diff.outputs.package_names), 'html-ui')
    with:
      workspace: html-ui
      path: packages/html-ui
    secrets: inherit

  react-ui:
    needs: diff
    if: contains(fromJSON(needs.diff.outputs.package_names), 'react-ui')
    uses: ./.github/workflows/chromatic.yml
    with:
      workspace: react-ui
      path: packages/react-ui
    secrets: inherit