name: Merge Check

on:
  push:
    branches:
      - renovate/*
  pull_request:
    branches-ignore: 
      - bitbucket
      - cherry-pick-*

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      base_ref: ${{ github.base_ref }}
    secrets: inherit

  finish:
    needs: ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: 'Check status of all required jobs'
        run: |-
          NEEDS_CONTEXT='${{ toJson(needs) }}'
          JOB_IDS=$(echo "$NEEDS_CONTEXT" | jq -r 'keys[]')
          for JOB_ID in $JOB_IDS; do
            RESULT=$(echo "$NEEDS_CONTEXT" | jq -r ".[\"$JOB_ID\"].result")
            echo "$JOB_ID job result: $RESULT"
            if [[ "$RESULT" != "success" && "$RESULT" != "skipped" ]]; then
              echo "***"
              echo "Error: The $JOB_ID job did not pass."
              exit 1
            fi
          done
          echo "All jobs passed or were skipped."
    