name: Pre-release

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: The branch name you wish to create for the release
        default: release-
        type: string
        required: true
      base_ref_sha:
        description: The ref that you wish to create a release for if different from workflow target

concurrency:
  group: ${{ github.workflow }}-${{ inputs.base_ref_sha || github.ref_name }}
  cancel-in-progress: true

jobs:
  prerelease:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ github.ref_name }}
    env:
      base_ref: ${{ inputs.base_ref_sha || github.ref_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 50
          ref: ${{ env.base_ref }}
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
      - name: Get branch name
        id: base_ref
        run: echo "name=$(git branch --show-current)" >> $GITHUB_OUTPUT
      - name: Setup Node.js environment
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - name: Override BASE_REF variable
        run: echo "BASE_REF=${{ env.base_ref }}" >> .env
      - name: Install dependencies
        run: |
          yarn install
          yarn bootstrap
      - name: Bump packages v0 to v1
        run: >-
          yarn workspaces foreach -A --no-private exec 'test $(yarn node -p "/^0\./.test(process.env.npm_package_version)") = true
          && yarn version major --deferred
          || echo "No major bump needed"'
      - name: Fix versions
        run: yarn fix-versions
      - name: "Create and publish release: ${{ vars.RELEASE_TAG }}"
        uses: ./.github/actions/release
        with:
          prerelease: "true"
          tag: ${{ vars.RELEASE_TAG }}
      - name: Push ${{ env.base_ref }}
        if: ${{ steps.base_ref.outputs.name != '' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git push
      - name: "Create ${{ inputs.ref_name }}"
        run: |
          git checkout -b ${{ inputs.ref_name }}
          git push --set-upstream origin ${{ inputs.ref_name }}
