name: Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - release-*

concurrency:
  group: pull-request-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-version:
    if: startsWith(github.ref_name, 'renovate/') != true && github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 50
      - name: Fetch ${{ github.base_ref }}
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Override BASE_REF variable
        run: echo "BASE_REF=origin/${{ github.base_ref }}" >> .env
      - name: Check versions
        run: yarn version check

  generate-version:
    if: failure() && startsWith(github.head_ref, 'issue/') || startsWith(github.head_ref, 'feature/')
    needs: check-version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      APPLY_STRATEGY: ${{ startsWith(github.head_ref, 'issue/') && 'patch' || 'minor' }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Configure git
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Check out code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 50
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
      - name: Fetch ${{ github.base_ref }}
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Setup Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Override BASE_REF variable
        run: echo "BASE_REF=origin/${{ github.base_ref }}" >> .env
      - name: Install dependencies
        run: |
          yarn install
          yarn bootstrap
      - name: Remove existing version strategies
        run: rm -rf .yarn/versions || true
      - name: Immediately bump versions
        id: versions
        run: echo "semver=$(yarn apply-versions --strategy ${{ env.APPLY_STRATEGY }})" >> $GITHUB_OUTPUT
      - name: Remove all changes
        run: git stash
      - name: Add version strategy to changed workspaces
        run: yarn workspaces foreach -A --no-private exec 'test $(echo $SEMVER | jq .\"$npm_package_name\") = null || yarn version ${{ env.APPLY_STRATEGY }} --deferred'
      - name: Push
        if: env.SEMVER != '' && env.SEMVER != '{}'
        run: |
          git add .
          git commit -m "chore(version): strategy"
          git push
        env:
          SEMVER: ${{ steps.versions.outputs.semver }}
