name: Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - release-*

concurrency:
  group: pull-request-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-version:
    if: startsWith(github.ref_name, 'renovate/') != true && github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2
      - name: Fetch ${{ github.base_ref }}
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Override BASE_REF variable
        run: echo "BASE_REF=origin/${{ github.base_ref }}" >> .env
      - name: Check versions
        run: yarn version check

  generate-version:
    if: failure()
    needs: check-version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      YARN_ENABLE_GLOBAL_CACHE: false
    steps:
      - name: Configure git
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
      - name: Setup Node.js environment
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - name: Override BASE_REF variable
        run: echo "BASE_REF=origin/${{ github.base_ref }}" >> .env
      - name: Install dependencies
        run: |
          yarn install
          yarn bootstrap
      - name: Fetch ${{ github.base_ref }}
        run: git fetch --depth=1 origin ${{ github.base_ref }}
      - name: Add version strategy
        run: yarn workspaces foreach --since --no-private version ${{ startsWith(github.head_ref, 'issue/') && 'patch' || 'minor' }} --deferred
      - name: Push
        run: |
          git add .
          git commit -m "chore(version): strategy" || true
          git push
