name: Pull Request

on:
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  check-version:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 50
      - name: Setup Node.js environment
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: ./yarn.lock
      - name: Fetch target branch
        run: git fetch --depth=1 origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Check versions
        run: yarn version check
