on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '7 7 * * *'
      timezone: America/Los_Angeles

permissions:
  contents: read

jobs:
  next:
    uses: ./.github/workflows/sync.yml
    with:
      ref_name: next
    secrets: inherit
