on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  test:
    name: Run Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: ${{ inputs.workspace }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Unpack binaries
        run: yarn install
      - name: Verify dependencies
        run: yarn bootstrap
      - name: Install Playwright
        run: yarn dlx playwright install --with-deps
      - name: Run Lint
        run: yarn lint
      - name: Run Coverage
        run: |
          yarn start --port 6006 --silent & \
          yarn dlx wait-on http://127.0.0.1:6006 && yarn test --coverage
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v3
        with:
          files: ${{ inputs.path }}/coverage/storybook/coverage-storybook.json
          flags: ${{ inputs.workspace }}
      - name: Run Chromatic
        run: yarn turbo chromatic