on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  chromatic:
    name: Run Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: ${{ inputs.workspace }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Unpack binaries
        run: yarn install
      - name: Verify dependencies
        run: yarn bootstrap
      - name: Run Chromatic
        run: yarn turbo chromatic --filter=${{inputs.workspace}}